a=int(input("dati numarul"))
b=int(input("dati numarul"))
c=int(input("dati numarul"))
if a%2==0:
    print(a," par")
if a%2!=0:
    print(a," impar")
if b%2==0:
    print(b," par")
if b%2!=0:
    print(b," impar")
if c%2==0:
    print(c," par")
if c%2!=0:
    print(c," impar")